apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-web-app-deployment
  labels:
    app:  python-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      containers:
      - name:  python-web-app
        image: richard92/my-python-app:latest
        ports:
        - containerPort: 5000

