apiVersion: v1
kind: Service
metadata:
  name: pythonwebapp
  namespace: pythonwebapp
spec:
  type: ClusterIP
  selector:
    app: python-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

